
FROM mcs07/postgres-rdkit

# data dump
# COPY compose/postgres/data/ChemMap_Dec.dump /docker-entrypoint-initdb.d/ChemMap_Dec.dump

# add postgres config
COPY compose/postgres/postgresql.conf /etc/postgresql/postgresql.conf

# ENV PGDATA=/data
# make them executable
#RUN chmod +x /usr/local/bin/app-backups && \
 

